site_name: CNCFrog User Manual
theme: 
  name: material
  logo: resources/LogoFull.webp
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.footer
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - toc.follow
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: blackfrog
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: blackfrog
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

nav:
  - index.md
  - Introduction:
    - Introduction/index.md
  - Assembly:
    - Assembly/index.md
    - Assembly/step1.md
    - Step2:
      - Assembly/Step2/index.md
      - Assembly/Step2/step2profileA.md
      - Assembly/Step2/step2profileB.md
      - Assembly/Step2/step2profileC.md
      - Assembly/Step2/step2profileD.md
      - Assembly/Step2/step2profileL+R.md
    - Step3:
      - Assembly/Step3/index.md
    - Step4:
      - Assembly/Step4/index.md
    - Step5:
      - Assembly/Step5/index.md
    - Step6:
      - Assembly/Step6/index.md
    - Step7:
      - Assembly/Step7/index.md
    - Step8:
      - Assembly/Step8/index.md
    - Step9:
      - Assembly/Step9/index.md
    - Step10:
      - Assembly/Step10/index.md
     

extra: 
  alternate:
    - name: English
      link: /MkDocsTest/en/
      lang: en
    - name: Polish
      link: /MkDocsTest/pl/
      lang: pl

extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

# https://pypi.org/project/mkdocs-with-pdf/
# https://github.com/ultrabug/mkdocs-static-i18n
plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: true
      caption_position: bottom
  - with-pdf:
      #author: WHO
      #copyright: ANY TEXT
      #
      #cover: false
      #back_cover: true
      #cover_title: TITLE TEXT
      #cover_subtitle: SUBTITLE TEXT
      #custom_template_path: TEMPLATES PATH
      #
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: 'C:\Program Files\Google\Chrome\Application\chrome.exe'
      #
      #output_path: any-place/document.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      show_anchors: true
      #verbose: true
  - i18n:
      default_language: en
      material_alternate: true
      nav_translations:
        pl:
          Introduction: Wstęp
          Assembly: Montaż
          Step2: Krok 2 - Przygotowanie profili v-slot ramy frezarki
          Step3: Krok 3 - Montaż ramy frezarki i zasilacza
          Step4: Krok 4 - Montaż płyty MDF do ramy frezarki
          Step5: Krok 5 - Montaż osi Z - mocowanie wrzeciona 
          Step6: Krok 6 - Montaż osi Z - montaż modułu Z 
          Step7: Krok 7 - Montaż osi X
          Step8: Krok 8 - Montaż osi X na ramie frezarki
          Step9: Krok 9 - Montaż krańcówek osi X Y Z
          Step10: Krok 10 - Montaż elektroniki
      languages:
        en:
          name: English
          site_name: CNCFrog User Manual
          build: true
        pl:
          name: Polski
          site_name: Instrukcja użytkownika CNCFrog
          build: true
  - git-revision-date-localized:
      enable_creation_date: true