site_name: CNC Router User Manual
site_url: https://bartshoot.github.io/MkDocsTest/
repo_url: https://github.com/BartShoot/MkDocsTest
repo_name: BartShoot/MKDocsTest
theme: 
  name: material
  logo: resources/LogoFull.png
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - toc.follow
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: blackfrog
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: blackfrog
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
extra: 
  alternate:
    - name: English
      link: /MkDocsTest/en/
      lang: en
    - name: Polish
      link: /MkDocsTest/pl/
      lang: pl

extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

# https://pypi.org/project/mkdocs-with-pdf/
# https://github.com/ultrabug/mkdocs-static-i18n
plugins:
  - search
  - i18n:
      default_language: en
      material_alternate: true
      nav_translations:
        pl:
          Introduction: Wstęp
      languages:
        en:
          name: English
          site_name: CNC Mill User Manual
          build: true
        pl:
          name: Polski
          site_name: Instrukcja obsługi użytkownika frezarki
          build: true
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       auto_caption: true
       caption_position: bottom
  - git-revision-date-localized:
      enable_creation_date: true
  - with-pdf:
        #author: WHO
        #copyright: ANY TEXT
        #
        #cover: false
        #back_cover: true
        #cover_title: TITLE TEXT
        #cover_subtitle: SUBTITLE TEXT
        #custom_template_path: TEMPLATES PATH
        #
        #toc_title: TOC TITLE TEXT
        #heading_shift: false
        #toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        #two_columns_level: 3
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
        #output_path: any-place/document.pdf
        enabled_if_env: ENABLE_PDF_EXPORT
        #
        #debug_html: true
        #show_anchors: true
        #verbose: true